// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN8veCcVQ5seXkPSl2xioSlz7RXzVot-M',
    appId: '1:204790043057:web:bc29a93fd57477859bad90',
    messagingSenderId: '204790043057',
    projectId: 'auth-with-fb-35feb',
    authDomain: 'auth-with-fb-35feb.firebaseapp.com',
    storageBucket: 'auth-with-fb-35feb.firebasestorage.app',
    measurementId: 'G-T9S99V058F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkK5qcrfoXOf5NFXKkewBhZ25jN2a5Vl4',
    appId: '1:204790043057:android:ae8053294d0d6cb59bad90',
    messagingSenderId: '204790043057',
    projectId: 'auth-with-fb-35feb',
    storageBucket: 'auth-with-fb-35feb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmGa2AgmAazuXIxK_5wX8h1GAzt3Tbe7Q',
    appId: '1:204790043057:ios:45a5e09e2caeba6f9bad90',
    messagingSenderId: '204790043057',
    projectId: 'auth-with-fb-35feb',
    storageBucket: 'auth-with-fb-35feb.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmGa2AgmAazuXIxK_5wX8h1GAzt3Tbe7Q',
    appId: '1:204790043057:ios:e206a28cfb88e85a9bad90',
    messagingSenderId: '204790043057',
    projectId: 'auth-with-fb-35feb',
    storageBucket: 'auth-with-fb-35feb.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN8veCcVQ5seXkPSl2xioSlz7RXzVot-M',
    appId: '1:204790043057:web:e6f514ce1b1666a49bad90',
    messagingSenderId: '204790043057',
    projectId: 'auth-with-fb-35feb',
    authDomain: 'auth-with-fb-35feb.firebaseapp.com',
    storageBucket: 'auth-with-fb-35feb.firebasestorage.app',
    measurementId: 'G-XZLPYE07KN',
  );
}
